test:
	yarn test

start:
	NODE_OPTIONS="--no-experimental-fetch --openssl-legacy-provider" yarn start

lint:
	npx eslint .

lint-fix:
	npx eslint --fix .

prettify-check:
	prettier --check .

prettify-fix:
	prettier --write .
